# Site settings
title: 胡慧琦的学术主页
email: your.email@university.edu
description: >-
  欢迎来到我的学术主页。我是一名专注于计算机科学研究的学者，
  致力于推动科技创新和学术发展。
baseurl: "/huhuiqi"
url: "https://iamrainyday.github.io"

# Personal information
author:
  name: 胡慧琦
  email: your.email@university.edu
  institution: 您的大学/机构名称
  department: 计算机科学系
  position: 副教授/研究员
  
# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
